-- Al Musafir for Car Rental — Car Rental Agreement storage
-- Matches the "CAR RENTAL AGREEMENT / عقد إيجار سيارة" template
-- (Second Party / Lessor = Al Musafir, fixed; First Party / Lessee = customer).
-- Import with: mysql -u root -p < schema.sql

CREATE DATABASE IF NOT EXISTS al_musafir_contracts
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE al_musafir_contracts;

DROP TABLE IF EXISTS contracts;

CREATE TABLE contracts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    -- Not printed on the template; kept for internal search/records.
    -- Generated by the app right after insert (format AM-YYYY-####
    -- based on the row's own id), so it is briefly NULL between the
    -- INSERT and the follow-up UPDATE — see save.php.
    contract_no VARCHAR(50) NULL,

    -- First Party (Lessee) — the customer
    lessee_name VARCHAR(255) NOT NULL,
    lessee_nationality VARCHAR(100) NULL,
    lessee_id_no VARCHAR(100) NULL,
    lessee_phone VARCHAR(50) NULL,

    -- Article 1: Vehicle
    veh_type VARCHAR(150) NULL,
    veh_plate_no VARCHAR(50) NOT NULL,
    veh_colour VARCHAR(50) NULL,
    veh_odometer VARCHAR(50) NULL,
    mileage_restricted ENUM('yes','no') NULL,
    allowed_mileage_km SMALLINT UNSIGNED NULL,

    -- Article 2: Rental period
    rental_days SMALLINT UNSIGNED NULL,
    rent_paid DECIMAL(10,2) NULL,
    rental_start_date DATE NOT NULL,
    rental_start_time TIME NULL,
    rental_end_date DATE NOT NULL,
    rental_end_time TIME NULL,

    -- Article 3: Security deposit
    security_deposit DECIMAL(10,2) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_contract_no (contract_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
